version: '3.7'
services:
  nextjs:
    # container_name: nextjs
    image: node:8.15.0-alpine
    ports:
      - "3000"
    volumes:
      - ../nextjs:/app/nextjs
      - ./logs/nextjs/npm:/root/.npm/_logs
    working_dir: /app/nextjs
    command: >
      /bin/sh -c "npm install -f&&
        npm run build &&
        npm run start"
  nginx:
    # container_name: nginx
    image: nginx:1.15.8-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    links:
      - nextjs
    restart: always